
# SEO settings
title: "netdex"
title2: "blog" # default: ""
description: "the pearls of my mental noise"
keywords: "netdex, blog, tech, reverse engineering, computer, programmer"
url: https://blog.netdex.cf # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-73692659-1
repo: http://github.com/netdex/blog.netdex.cf
disqus_shortname: "hnbloggithub"
twitter_username: "HeiswayiNrird"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Gordon Guan"
  job      : "amateur programmer"
  bio      : "please enjoy my neural noise"
  thumb    : /images/author.jpg
  email    : admin@netdex.cf
  url      : https://netdex.cf
  github   : http://github.com/netdex
  twitter  : http://twitter.com/netdex
#  facebook : 
#  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@netdex"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
