
# SEO settings
title: "netdex"
title2: "blog" # default: ""
description: "the pearls of my mental noise"
keywords: "netdex, blog, tech, reverse engineering, computer, programmer"
url: https://blog.netdex.cf # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-73692659-1
repo: http://github.com/netdex/blog.netdex.cf
#disqus_shortname: ""
#twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "netdex"
  job      : "programmer, tech enthusiast, netsec fanatic, reverse engineer etc, etc."
  bio      : "I do interesting things sometimes. If they're especially interesting, I'll log them here."
  thumb    : /images/author.jpg
  email    : admin@netdex.cf
  url      : https://netdex.cf
  github   : http://github.com/netdex
#  twitter  : 
#  facebook : 
#  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@netdex"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
